package ar.edu.unlp.CellularAutomaton.view;

import java.awt.Event;

/**
 * Event class for gridPanel
 * Objects from this class are generated by GridPanel
 * @see GridPanel
 * @author mclo
 */
public class GridPanelEvent extends Event {
	
	private int cols;
	private int rows;
	
	private static final long serialVersionUID = 1L;

	/**
	 * Constructor
	 * @param target source of event
	 */
	public GridPanelEvent(Object target) {
		super(target, 0, null);
	}
	
	/**
	 * Constructs a event due to the size changed.
	 * @param target source of the event
	 * @param cols number of columns
	 * @param rows number of rows
	 * @return new event object
	 */
	public static GridPanelEvent getSizeChangedEvent(Object target, int cols, int rows){
		GridPanelEvent gridPanelEvent= new GridPanelEvent(target);
		gridPanelEvent.setCols(cols);
		gridPanelEvent.setRows(rows);
		return gridPanelEvent;
	}

	/**
	 * @return number of columns
	 */
	public int getCols() {
		return cols;
	}

	/**
	 * @param cols number of columns
	 */
	public void setCols(int cols) {
		this.cols = cols;
	}

	/**
	 * @return number of rows
	 */
	public int getRows() {
		return rows;
	}

	/**
	 * @param rows number of rows
	 */
	public void setRows(int rows) {
		this.rows = rows;
	}
}
